"""empty message

Revision ID: 05034a90809d
Revises: 22b8e0999267
Create Date: 2019-06-04 17:02:27.451432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05034a90809d'
down_revision = '22b8e0999267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'create_time')
    # ### end Alembic commands ###
